swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    aaa<svg/onload=prompt(/OPENBUGBOUNTY/)>

  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
