swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    aaa</div></div></div><div id=x tabindex=1 onfocus=alert(1)></div><div id=x tabindex=1 onfocus=alert(1)></div><div id=x tabindex=1 onfocus=alert(1)></div>

  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
