swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    aaa%3Cform%20id%3D%22test%22%3E%3C%2Fform%3E%3Cbutton%20form%3D%22test%22%20formaction%3D%22javascript%3Aalert(1)%22%3EX%3C%2Fbutton%3E

  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
