swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    aaa<a>b</a>

  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
